
  repoName: "GitHub"
  projectType: "Java"
  nodeVersion: "openjdk:latest"
  selectedActions:
    - github_name: "my-java-repo"
      on:
        push:
          branches:
            - "main"
        pull:
          branches: []
        pull_request:
          branches: []
      git_jobs:
        - build:
            runs-on: "ubuntu-latest"
            steps:
              - name: "Checkout"
                Use: "actions/checkout@v2"
              - name: "Setup Java"
                Use: "actions/setup-java@v3"
              - name: "Compile"
                Run: "mvn compile"
              - name: "Test"
                Run: "mvn test"
